#! /bin/sh


### AUTOSTART ###

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
feh --bg-fill $HOME/.config/wallpaper/wallpaper.jpg &
$HOME/.config/polybar/launch.sh &
pgrep -x xbindkeys > /dev/null || xbindkeys &


# bspc rule -a firefoxdeveloperedition state=floating rectangle=1920x1080+100+100


bspc config border_width        1
bspc config window_gap          24
# bspc config split_ratio         0.52

bspc config automatic_scheme alternate

#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
#bspc config single_monocle	 true
#bspc config ignore_ewmh_focus	 true

### WORKSPACES ###


bspc monitor -d 1 2 3 4 5 6 7 8 9 0


### WINDOW RULES ###

bspc rule -a firefoxdeveloperedition desktop=1 follow=on
bspc rule -a Code desktop=2 follow=on
bspc rule -a URxvt desktop=3 follow=on
bspc rule -a google-chrome desktop=7 follow=on
bspc rule -a Spotify desktop=9

bspc rule -a lxappearance state=floating rectangle=1920x1080+100+100


# Set the border colors.
# bspc config normal_border_color "$color1"
# bspc config active_border_color "$color2"
# bspc config focused_border_color "$color15"

# bspc config presel_feedback_color "$color1"



###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window

bspc config external_rules_command "$HOME/.bin/bspwm-external-rules"